// Wordlock word banks. Edit or extend these freely.
// Loaded as a plain global so the app works offline from a double-clicked index.html
// (browsers block fetch() of local files, but classic <script> tags load fine).
window.WORDLOCK_BANKS = {
  Space:["nebula","comet","quasar","orbit","lunar","meteor","cosmos","photon","pulsar","eclipse","galaxy","rocket","stellar","gravity","plasma","aurora","crater","saturn","neutron","asteroid","cosmic","satellite","telescope","horizon","voyager","gamma","helium","solar","beacon","vortex","zenith","parsec","radiant","halo","flare","supernova","void","signal","thruster","rover","lander","tether","glide","ion","drift","module","cradle","airlock","gantry","apogee"],
  Nature:["canyon","willow","meadow","glacier","thunder","pebble","cedar","lichen","marsh","summit","ridge","fern","birch","maple","tundra","prairie","delta","reef","dune","basin","hollow","grove","brook","amber","harvest","autumn","drizzle","breeze","cliff","valley","boulder","current","frost","gully","hazel","juniper","kelp","lagoon","mist","oasis","petal","quartz","river","spruce","thicket","vine","wildflower","canopy","gravel","tidepool"],
  Mythos:["phoenix","kraken","sphinx","titan","oracle","hydra","pegasus","golem","valkyrie","chimera","griffin","basilisk","minotaur","siren","cyclops","harpy","gorgon","nymph","druid","wraith","banshee","djinn","fenrir","atlas","charon","helios","juno","medusa","nereid","selene","wyvern","anubis","cerberus","dryad","glaive","idol","mantle","omen","relic","runic","talisman","centaur","leviathan","seraph","nemesis","mythic","obelisk","scepter","emberfox","starlance"],
  Food:["waffle","pretzel","mango","basil","walnut","pickle","cobbler","biscuit","custard","noodle","paprika","saffron","brioche","cherry","donut","espresso","ginger","honey","jalapeno","lychee","melon","nutmeg","olive","peach","quinoa","radish","sesame","truffle","vanilla","wasabi","almond","brisket","churro","dumpling","eclair","falafel","gnocchi","hummus","pesto","ramen","sorbet","tahini","sundae","scone","praline","mango","tangelo","brittle","caramel","clementine"],
  Animals:["otter","badger","falcon","gecko","heron","jaguar","lemur","marmot","narwhal","ocelot","panther","raven","salmon","tapir","urchin","viper","walrus","bison","cobra","dingo","egret","ferret","gibbon","hyena","ibis","koala","lynx","mongoose","newt","osprey","puffin","quail","stoat","toucan","weasel","antelope","beaver","condor","dolphin","finch","gopher","impala","jackal","kestrel","llama","manta","pelican","raccoon","skylark","wombat"],
  Music:["rhythm","tempo","ballad","octave","treble","anthem","encore","fugue","harmony","lyric","melody","sonata","vibrato","chorus","banjo","cadence","dulcimer","forte","groove","jingle","kazoo","lullaby","mandolin","nocturne","oboe","prelude","quaver","refrain","staccato","timbre","ukulele","waltz","allegro","bassline","crescendo","downbeat","ensemble","falsetto","gospel","interlude","libretto","motif","opus","reverb","syncopate","arpeggio","overture","rondo","cymbal","whistle"],
  Common:["anchor","apple","arrow","bakery","balance","balloon","bamboo","bandage","barrel","basket","battery","bedroom","bench","bicycle","blanket","bonfire","bottle","bracket","branch","breakfast","bridge","bubble","bucket","buckle","button","cabin","cactus","camera","candle","canvas","captain","cargo","carpet","castle","ceiling","cellar","chimney","circus","clarinet","clever","clock","closet","clover","cluster","compass","copper","cottage","cousin","cracker","crayon","crowd","crystal","cushion","dancer","daylight","denim","diamond","doorway","dragon","drawer","drawing","dresser","earring","easel","engine","envelope","eraser","factory","farmer","feather","fiddle","fireplace","flannel","flagpole","flashlight","fountain","freezer","garden","garland","gateway","granite","hamlet","hammer","hammock","handle","harbor","helmet","hexagon","hillside","hinge","holiday","hospital","hostel","jacket","jungle","kettle","keyboard","kingdom","kitchen","kitten","ladder","laundry","lavender","leather","lecture","library","lighthouse","lobby","locket","lumber","magnet","mailbox","mansion","marble","marigold","market","mirror","mitten","monarch","morning","mountain","muffin","napkin","necklace","network","notebook","oatmeal","orchard","ostrich","package","paddle","painter","pancake","parlor","pasture","pendant","penguin","pepper","picture","pigeon","pillow","pioneer","pitcher","planet","plumber","pocket","pottery","printer","puddle","pumpkin","puzzle","railway","rainbow","ranch","rattle","recital","ribbon","rooster","sailor","sandbox","sapphire","satchel","saucer","scarf","scissors","seashell","season","shelter","shovel","silver","slipper","snowfall","soldier","sparrow","speaker","spindle","sponge","spotlight","stadium","station","stencil","stitch","stove","student","sunrise","sunset","sweater","syrup","teacup","teapot","theater","thimble","ticket","timber","toaster","tractor","trumpet","tunnel","turtle","umbrella","vendor","village","violet","voyage","wagon","wardrobe","window","winter","wizard","wonder","zebra","zipper"]
};
